### ISSUE TITLE
Think about how module resolving should work

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#15]
There are a few things to think about for our module resolving:

1. Should the import below look into the module directory for foo.js?
```
import foo from 'foo';
```
That's what we do today. And it's not valid considering v8 will not resolve the same module specifier twice: https://github.com/ry/v8worker2/blob/master/binding.cc#L266

2. Probably more, but brain needs a pause from thinking about modules

**Comment by squaremo** [comment]
> And it's not valid considering v8 will not resolve the same module specifier twice

Would you elaborate on why it's not valid?

There are certainly related problems introduced by how V8Worker2's LoadModule is implemented: specifically, it requires that the resolver callback calls `LoadModule` with the specifier exactly as given (otherwise it will regard it as not having loaded, afterward); but, it doesn't canonicalise them, meaning that has to be done in the resolver (otherwise the same module, referred to by different paths, will be re-initialised).

**Comment by dlespiau** [comment]
There are two things intermixed in that comment:

- should `import * from 'foo';` work when we mean `import * from './foo'`
- v8worker2 seems to be caching specifiers that have already been resolved, if I have two files in two different directories both doing `import * from './foo`, the way I read the code/comment is that the second `./foo` will not try to be resolved and we'll use the first `foo.js` for the second file. Easier way is to test it I guess.

**Comment by dlespiau** [comment]
We now have a good grasp on this and @squaremo just fixed the relative import with identical specifiers  issue. Let's close it! More precise issues should be opened when needed.
