### ISSUE TITLE
output dependencies

### ISSUE THREAD

**Issue by bryanlarsen** [jkcfg/jk#172]
splitting this out from #165.

To use jk in a dev environment like skaffold or make we need some way to determine the list of dependencies, sort of like gcc's -MM option.  https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/GCC/options/MM

this should list stuff that is imported and std.read'd.

**Comment by dlespiau** [comment]
That sounds like something not to hard to do and I can see it being useful, absolutely!

We'd probably want that information easily parseable. We could add metadata as well so maybe a bit more than just one file per line say, a json array objects. Maybe not useful for your use case but we could indicate if the file is a dependency because it's imported, used in `std.read` or a resource (a feature not yet documented, sorry!)

**Comment by dlespiau** [comment]
To be clear, I'll look into this and should have something this week.

**Comment by dlespiau** [comment]
Have something: https://github.com/jkcfg/jk/pull/173. Would that be enough for your use case?

**Comment by dlespiau** [comment]
Probably a good idea to look at the skaffold interface so we don't have too much impedance mismatch between what they expect and what we provide. Do you have a link handy? I'll dig into skaffold otherwise.

On case that we have to watch out for: when a `.js` (and maybe later `.ts`) file changes, we also have to re-query for the list of dependencies because the user could have just added an `import` line in the js file.

**Comment by bryanlarsen** [comment]
#173 looks like it would work.

the corresponding function for kustomize on skaffold is dependenciesForKustomization : https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kustomize.go

when I add a file to kustomization.yaml, skaffold picks it up, so I think skaffold is already rescanning dependencies when a dependency changes.

**Comment by dlespiau** [comment]
Alright merged it with the addition of a 3rd source of input files (the `run -f` option). We don't make stability guarantees before 1.0.0 (but only introduce backward incompatible changes in 0.x.0 versions) so we can tweak this if needed.
