### ISSUE TITLE
Error: reads outside base path forbidden

### ISSUE THREAD

**Issue by bryanlarsen** [jkcfg/jk#306]
Is there a way to disable the "Error: reads outside base path forbidden" check?

I'm trying to `std.read("../../manifest.json")`, but it throws that error.   

I used to work around this misfeature by creating a manifest.js that contains `import { read } from '@jkcfg/std/resource'; export default read('manifest.json');`

However that doesn't work very well if manifest.json may not exist.  We can wrap the `await` in a try block, but since the Promise is created in an import, it may resolve before we get to the await and we get the "Error: reads outside base path forbidden" problem.

And the '-i' option doesn't work either because we want to std.read from both the scripts and the data directory.   It also makes running the jk script ad-hoc unfriendly.

**Comment by squaremo** [comment]
Bryan, I mostly get what you're saying, but I can't quite picture what you mean by 

> we want to std.read from both the scripts and the data directory

Are `scripts` and `data` two directories in different parts of the filesystem? A sketch of the directory structure (with those two things, and the script you're running, and the manifests.json) would help.

> We can wrap the `await` in a try block, but since the Promise is created in an import, it may resolve before we get to the await and we get the "Error: reads outside base path forbidden" problem.

Not sure I get this bit either -- if the point of putting a module around the manifest is that it can live outside the input directory, surely you wouldn't ever get the "reads outside base path" error? (though you might get a "file does not exist" error)

**Comment by bryanlarsen** [comment]
> Are scripts and data two directories in different parts of the filesystem?

manifest.json exists in the root directory along with manifest.js and the scripts are in the "infra/jk" directory.   They do always have a common root that can be supplied to "-d", my main objection to "-d" is that it's not intuitive that "File Not Found" means "please supply the -d option".

infra/jk/resources.js contains:

```
import manifestJs from '../../manifest';

export async function preUpdate() {
  let manifest = null;
  try {
    manifest = await manifestJs;
  } catch (e) {}
```

manifest.js:

```
import { read } from '@jkcfg/std/resource';

export default read('manifest.json');
```

> > We can wrap the await in a try block, but since the Promise is created in an import, it may resolve before we get to the await and we get the "Error: reads outside base path forbidden" problem.

> Not sure I get this bit either -- if the point of putting a module around the manifest is that it can live outside the input directory, surely you wouldn't ever get the "reads outside base path" error? (though you might get a "file does not exist" error)

I guess I should have described symptoms rather than guessing at the cause here, but I'm not getting deterministic behaviour from the above code.  Sometimes the try catch block catches the error, and sometimes I get the following crash and backtrace:

```
Promise rejected at undefined 0:0
Error: reads outside base path forbidden
    at recv (@jkcfg/std/internal/deferred.js:22:21)
    at requestAsPromise (@jkcfg/std/internal/deferred.js:64:34)
    at Module.read (@jkcfg/std/read.js:54:12)
    at install (/home/blarsen/threekit/infra/jk/resources.js:153:40)
```

**Comment by squaremo** [comment]
> I guess I should have described symptoms rather than guessing at the cause here, but I'm not getting deterministic behaviour from the above code. Sometimes the try catch block catches the error, and sometimes I get the following crash and backtrace:
> 
> ```
> Promise rejected at undefined 0:0
> Error: reads outside base path forbidden
>     at recv (@jkcfg/std/internal/deferred.js:22:21)
>     at requestAsPromise (@jkcfg/std/internal/deferred.js:64:34)
>     at Module.read (@jkcfg/std/read.js:54:12)
>     at install (/home/blarsen/threekit/infra/jk/resources.js:153:40)
> ```

Ah right -- well that's a bug, which ought to be fixed, whatever else happens. I'll come up with a test case.

**Comment by squaremo** [comment]
> manifest.json exists in the root directory along with manifest.js and the scripts are in the "infra/jk" directory. They do always have a common root that can be supplied to "-d", my main objection to "-d" is that it's not intuitive that "File Not Found" means "please supply the -d option".

(assuming `-i,--input-directory` rather than `-d,--emit-dependencies`)

So let's see, that's something like this:

```
$ tree .
.
├── infra
│   └── jk
│       └── resources.js
├── manifest.js
└── manifest.json
```

If I adapt the example code a little to make resources.js a complete program, I can run this (from `.`) with `jk run ./infra/jk/resources.js` and it'll succeed. I guess you also want to target the script at different sets of data, and be able to do `jk run -i prod ./infra/jk/resources.js` (and in fact, run it from more or less anywhere and get the right answer). `manifest.json` is common to all the data, so you want to include it regardless the input directory is.

Your objection, I think, is that it's not easy to get the right combination of `-i` along with where you're running it, how your files are set out in directories, and how modules are resolved; in particular, it seems overly constraining, and when it's not all lined up, it's not clear why.

I think this is a reasonable criticism, and the formulation of `--input-directory` etc., is an area we're still feeling our way through. There's a strong preference for keeping things sandboxed -- that's the motivation behind disallowing reads outside the input directory. But if we want to hold close to that, we should at least be clear about why things fail and how to work in sympathy with the constraints.

In this case, wrapping the `manifests.json` in a module so you can import it is the expected way to share common data. If you could read outside the input directory, you would still have the problem that it would always have to be at `../../manifest.json` in relation to the input directory, so you'd not be in a different position to now. It is likely to be more convenient for it to be in a fixed place with respect to the script you are running, and let module resolution find it. Being able to control module resolution better would help with this too (so you could target common data from more than one source, for example).

**Comment by squaremo** [comment]
> > I guess I should have described symptoms rather than guessing at the cause here, but I'm not getting deterministic behaviour from the above code. Sometimes the try catch block catches the error, and sometimes I get the following crash and backtrace:
> > ```
> > Promise rejected at undefined 0:0
> > Error: reads outside base path forbidden
> >     at recv (@jkcfg/std/internal/deferred.js:22:21)
> >     at requestAsPromise (@jkcfg/std/internal/deferred.js:64:34)
> >     at Module.read (@jkcfg/std/read.js:54:12)
> >     at install (/home/blarsen/threekit/infra/jk/resources.js:153:40)
> > ```
> 
> Ah right -- well that's a bug, which ought to be fixed, whatever else happens. I'll come up with a test case.

My naive test case (which closely follows the example snippets) does not fail. What else is happening in resources.js, presumably other `read`s? Could it be one of those be failing? (Again, I accept your argument that the causes of failures are unclear!)

**Comment by bryanlarsen** [comment]
You have to love undeterministic bugs.   Of course I can't make it trigger today.   Is there a setTimeout or sleep or something in JK so I can play with delays?

I'm fairly sure my theory about the cause is wrong; AFAIK, unhandled promise rejections do not throw errors until program exit.   If so, please ignore any silly theories I expounded above.  :)

**Comment by bryanlarsen** [comment]
I'm still unable to reproduce.  I'm going to close as PBKAC and re-open if I experience it again.

**Comment by squaremo** [comment]
> You have to love undeterministic bugs. Of course I can't make it trigger today. Is there a setTimeout or sleep or something in JK so I can play with delays?

Most things in the standard library that are represented by a Promise are run in their own goroutine in the runtime, so there is definitely non-determinism in terms of scheduling. But we do take care to resolve promises in the same order they were created, which removes the scheduling from the equation -- it should not be possible to get different results from Promises resolving in a different order.

There's no timers, because they would introduce non-determinism (ironically).

**Comment by squaremo** [comment]
> If I adapt the example code a little to make resources.js a complete program, I can run this (from `.`) with `jk run ./infra/jk/resources.js` and it'll succeed. I guess you also want to target the script at different sets of data, and be able to do `jk run -i prod ./infra/jk/resources.js` (and in fact, run it from more or less anywhere and get the right answer). `manifest.json` is common to all the data, so you want to include it regardless the input directory is.
> 
> Your objection, I think, is that it's not easy to get the right combination of `-i` along with where you're running it, how your files are set out in directories, and how modules are resolved; in particular, it seems overly constraining, and when it's not all lined up, it's not clear why.
> 
> I think this is a reasonable criticism, and the formulation of `--input-directory` etc., is an area we're still feeling our way through. There's a strong preference for keeping things sandboxed -- that's the motivation behind disallowing reads outside the input directory. But if we want to hold close to that, we should at least be clear about why things fail and how to work in sympathy with the constraints.

If you have further comments or suggestions on the above, they would be most welcome. (But if you just want to get on with things, that would be fair!)

**Comment by squaremo** [comment]
I should also say: thank you for persevering -- people who carefully report issues and follow them up don't get thanked enough :-)
